### ISSUE TITLE
Unable to see preview if hardwareRotation = false and rotation = 90

### ISSUE THREAD

**Issue by kabunov** [pedroSG94/rtmp-rtsp-stream-client-java#101] opened 2017-12-14 06:08 UTC
Hi,

I'm trying to modify the SurfaceModeRtmpActivity, I set

    if (rtmpCamera2.prepareAudio() && rtmpCamera2.prepareVideo(640, 480, 30, 1200 * 1024, false, 90)) {
       
instead of

    if (rtmpCamera2.prepareAudio() && rtmpCamera2.prepareVideo()) {

to set the rotation.

After that the app doesn't show the preview, just black screen. 

I debugged and seems the onConfigureFailed callback is calling (Camera2ApiManager line 121).

I guess that the app tries to show the preview for rotated size 480x640, and its failed.
From docs:
https://developer.android.com/reference/android/hardware/camera2/CameraCaptureSession.StateCallback.html#onConfigureFailed(android.hardware.camera2.CameraCaptureSession)
>This can happen if the set of requested outputs contains unsupported sizes, or too many outputs are requested at once.

Could you please check what's the best way to fix this?

**Comment by pedroSG94** [comment] 2017-12-14 09:41
Yes this is my fault. I should delete software rotation option in camera2 because you can't rotate it with software (because you are doing encoding by surface and rotate by software only work with encoding by buffer) only with hardware, The problem is that some devices ignore it.
If you want reproduce default config you should write:
```java
rtmpCamera2.prepareVideo(640, 480, 30, 1200 * 1024, true, 90);
```

I will fix it and create a valid rotation for all devices using OpenglView with camera2.

**Comment by kabunov** [comment] 2017-12-14 09:54
Thanks for the quick response.
The thing is that my server doesn't support "rotation-degrees" attribute, that's why I tried to change the size or rotate with software.
Am I correct that the only way to do this is using OpenglView?

**Comment by pedroSG94** [comment] 2017-12-14 10:25
Yes, I did a little fix to work with camera2: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/465095183fc672a001927b3a47750baa0def78b2
The correct configuration for preparevideo is:
```java
rtmpCamera2.prepareVideo(640, 480, 30, 1200 * 1024, false, 90);
```
You could see a bad camera result like low resolution on preview and stream. I will try fix it but look a error on the CameraManager configuration.

**Comment by pedroSG94** [comment] 2017-12-14 18:39
Error resolution in camera2 with opengl is now fixed, also you have methods to know all resolution supported like in camera1: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/29db5dddf06112aae3df68553c00fde042e4a488
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/c9bc3586ccd712392cb9d5ad9d120d41a6b595dc

**Closed** 2017-12-23 22:14 UTC
