### ISSUE TITLE
Video Audio decode Error

### ISSUE THREAD

**Issue by MohammadRezaei92** [pedroSG94/rtmp-rtsp-stream-client-java#460] opened 2019-12-06 19:52 UTC
I use this library in my app and my app have released, but still I got error for audio, video encoding and decoding. I have been using version 1.5.8 and it's more stable than newer ones for me.
Here are my the most common errors:
![Alt Text](https://kkrrqa.bn.files.1drv.com/y4m0WoH5uYTjtDhEWpXrv8nAvWHZGhVLMfuPxA0wr7wAJoYIqY13gFgkewhzBOZx4ckz-NIGKAsRWQRnDGlxGfm080mMgfY1b3tG_fCkjneRmHus6tkAl2dXOMMH4PinU8rT89p1NKLHJckGsa1Wc9b6MAEnxg66SuTH55LnIX3DO06DMZDNbc7gk2bniDwbNzys0YIEWffLX4g_3sBLbXNYA?width=1081&height=569&cropmode=none)
![Alt Text](https://kqrrqa.bn.files.1drv.com/y4ml10e9sq3JokanTBM4qss4ku2GsCi8im2G2Jl1p98sbzdQVBxMgAtkwHSYsIyI_KZBYWZMdFpKa9MlW7Xjbohr5Kqi8T7BFqs_kp6sJ-8hrkmJ_x-4VIIlWGQERiJ_iIBkTvDU2X-wZ2ReESXlCOmIYZiWU6vJtmPk8Kd3Gxvlhhm_fKjCM2yXTwlZDNmQ6c5cp7Osd6sKMcxFjmpyfG7gg?width=1085&height=567&cropmode=none)

**Comment by pedroSG94** [comment] 2019-12-06 20:39
Hello, 

I can supose that you are using fromfile mode, right?
About video or audio encoder error that should be fixed in last version of library.
You are right that 1.6.x library versions was unstable with encoders, but in version 1.7.2 it seems more stable since I changed encoders logic and fixed fails. Decoders is unchanged, but I did somes fixs.
Audio decoder error should be fixed with this change.
Your version:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/c85a1959c5aea2040d86964ebaf025972a7ee936/encoder/src/main/java/com/pedro/encoder/input/decoder/AudioDecoder.java#L159
To master branch:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/decoder/AudioDecoder.java#L166

Let me know if you have any error with version 1.7.2 and I will fix it.

**Comment by MohammadRezaei92** [comment] 2019-12-07 18:47
> Hello,
> 
> I can supose that you are using fromfile mode, right?
> About video or audio encoder error that should be fixed in last version of library.
> You are right that 1.6.x library versions was unstable with encoders, but in version 1.7.2 it seems more stable since I changed encoders logic and fixed fails. Decoders is unchanged, but I did somes fixs.
> Audio decoder error should be fixed with this change.
> Your version:
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/c85a1959c5aea2040d86964ebaf025972a7ee936/encoder/src/main/java/com/pedro/encoder/input/decoder/AudioDecoder.java#L159
> To master branch:
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/decoder/AudioDecoder.java#L166
> 
> Let me know if you have any error with version 1.7.2 and I will fix it.

Yes, I am using fromFile. I changed the version to 1.7.2 once time and I got error for files that I could stream them with version 1.5.8. So I decided to decrease version to 1.5.8 again. I don't know but I think 2 versions have problems with some different kinds of video format.
Here are the error that I got for a video that can stream it with 1.5.8 but can't with 1.7.2:
`java.nio.BufferUnderflowException
        at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:240)
        at com.pedro.encoder.input.decoder.AudioDecoder.decodeAudio(AudioDecoder.java:166)
        at com.pedro.encoder.input.decoder.AudioDecoder.access$000(AudioDecoder.java:16)
        at com.pedro.encoder.input.decoder.AudioDecoder$1.run(AudioDecoder.java:96)`
Thank you for your time

**Comment by pedroSG94** [comment] 2019-12-07 20:17
Fixed here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/eee4697b0823c9f6932515fc583593e5fc8eb14a
Try with version 1.7.3.

**Comment by MohammadRezaei92** [comment] 2019-12-09 05:19
> Fixed here:
> [eee4697](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/eee4697b0823c9f6932515fc583593e5fc8eb14a)
> can you try with version 1.7.3?

It fixed in 1.7.3 thank you @pedroSG94

**Comment by MohammadRezaei92** [comment] 2019-12-13 08:11
Hi @pedroSG94. I released a new version of my app with new 1.7.3 library, unfortunately, I got a bunch of errors
![](https://k6tqyw.bn.files.1drv.com/y4mentS9VBgjRibNW9kHrnYSDQ9hsnh1s97JSmzfoFCKddnPB7y0RRcmOrnhvNC19btp3fLZimyRAhettgQT3RiEtY-k8caw10eSRdjCswT1BoZ6froBEoWS7WdZRrU7a4r8AfMG-jgcg5GtuxnITQ3qZPai_fyyPBRUvVgubXWnhrSzIBExMMjodX1PFR8rhvxuRknLIjmTSYL5oh1xAFM9g?width=1033&height=407&cropmode=none)
![](https://lqtqyw.bn.files.1drv.com/y4mutbfXqIZQRijYwK0i-lFa37zh0A_HJ6KgEhbE4gfR8vqbfy9BPp0uvtyM_ituDr8f__6V6edMduNwacH5JzrLl5w43vpnaFfYNcgdExcGRrb63romSiNyPh2oAEGVDL0cngUXnvSgZ5T2UQEUE_dzYR1Ht6-YZKDU8XYvvtWEKxMwaS5YFi2vYrx5q53c9AnxZVI3cQmx3S9F37FzuVE2Q?width=1024&height=438&cropmode=none)
![](https://jqrrqa.bn.files.1drv.com/y4m6e2GTPD4OXyAPgFLprKKaMuXVkVAcBcNA7ewpErknZzVKu00ArjVekEepFALx5-ir6nbg5Ol0XrMNfumFEI-1KbXdtWCiIugxgFcLPBO0ESNJg-jlTR-67cW_Uz9WpVN0IIH5bDJ3n4FZx-BEzr3qo9dgTGVDZ7xLYTMsaNK79E9_y5OY4rUUGURag_i_Cu0-sWnIvAxu5LfnbdbDyJtSw?width=1024&height=510&cropmode=none)
![](https://latqyw.bn.files.1drv.com/y4me4ClY1YVO8__ez1JDcYXU72ugAvaF7y2uLMzFtgjMLYECBw-NXotwn5N8_9sJ8CByTWlDImF04Sx8I30kf4QdUuBMeUs2eijd_1DEVVNfF0TD6PumNI68-iGFJVFuGY7GQCAiVPOm49SL7bBX2TFIoz88du7w5SAAH5RJTxu9hUSBcwQXvdGkArQMmMTtQKogKirzZGogIe9TYD5kUohgw?width=1024&height=524&cropmode=none)
![](https://lktqyw.bn.files.1drv.com/y4m4ZAbZgTgojB4jIakJNzqfoE7xADfO7sSdJahY03RnVJ75ktNacRw-bMjPSdLW-iY9dcbZWzyZESFXL31Jwg5v9fgxyGeaoEqITuJSrFSIO4j3SrevacismX5aEMlKitR85laLkedLjGAb_UKPhNhgTo0cgLf_cQsLgQsY-nEH2K3bODwGYTfhEYUKUzYdjCuRahql2wBBd6yWTiYDDogTg?width=1032&height=471&cropmode=none)
![](https://jarrqa.bn.files.1drv.com/y4mT6c2trB0Cekx9j44UGXTa9wqz2Vdi7Aoeh8yCgyhxW7OZ86JygsC4768term5rBq5YCNCqV-yHE2YxsTWwywJ_hdxYoxlIEVgfFBMO0CivXrMPbuD64XTi0yKPXmdQ-8x0JpyJ63iPJhYWYGeBSb1sFPUOBr8JPFr0QBJZF7qKOxmb2UioW423c0M1uYRgIxmqZR2THxfeyHARfWcY21tg?width=1048&height=549&cropmode=none)

**Comment by pedroSG94** [comment] 2019-12-13 09:31
This should be fixed here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/0c87c996a2c55b19e18903dd176fb0a39c152be5
Let me know if you have more problems.

**Comment by MohammadRezaei92** [comment] 2019-12-22 07:47
> This should be fixed here:
> [0c87c99](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/0c87c996a2c55b19e18903dd176fb0a39c152be5)
> Let me know if you have more problems.

I released a new version of my app with 1.7.4 library version, but I still have all same errors from the previous version. ☹

**Comment by pedroSG94** [comment] 2019-12-22 14:01
Can you share crash logcat?
The error should be in other line because I did null check to solved 2 of them and I did try catch to others.

**Comment by MohammadRezaei92** [comment] 2019-12-23 10:05
> Can you share crash logcat?
> The error should be in other line because I did null check to solved 2 of them and I did try catch to others.

Yes you right, you did null check and try catch, but ist's very weird that errors happened in same lines.

**Comment by pedroSG94** [comment] 2019-12-23 10:13
Can you check that app version is updated and user is not using old version?
For example null error now must be in line 164:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/decoder/AudioDecoder.java#L164
If you get null error in line 156 that means that you are using a old version of library.
Same for illegalstate, now in line 149:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/decoder/AudioDecoder.java#L149

**Comment by MohammadRezaei92** [comment] 2019-12-23 15:53
![](https://kktqyw.bn.files.1drv.com/y4mizrE49-AIsT6MjA_pw8wkguteF64Uiap3_qz8PsUvU2xFd-Ix8w8NEO-TQOo_yv6s6OdmMdPX7u0cFlxjdawqXF9ccHuuKrBgm3oF0pgw_Za52a3bF4A7EQ90_IZ71-jkE62c4OVmQs7HUT6liVjYtUG1dp9O5dkeALUTfx0bIs428RtbHxTolR338yhD_XLESaFNP-qUu7ivcshEvRM6w?width=1066&height=475&cropmode=none)
![](https://j6tqyw.bn.files.1drv.com/y4mVAle99Wt4pJf3hKFhXuy-NhmhyaGClyq5EzwaS8LwODlvJo4LfYvaX4BIDI3aLubiah_5seR4_J7rNxWu3pk_G4-GrZex1FPttWyAVwUhj-f29EeQHgB-7SVdIRAOYwG4IjCScigTEs9qCo96o4YsGFsPjanNfMcP7D8dZ2nFdc74BNVuHdxpss4DkMRjeGkSlFCx3GfRBD2NiO9Xin8gA?width=1057&height=468&cropmode=none)
![](https://jatqyw.bn.files.1drv.com/y4mZc4EayAL093G1tpGpNVpibBSmfaZW_vH5xhqnHhWJqd4RVx83nsJHPOdvSmq0fyf88kB1BokehpYCA97EcGK3dktYmlKQYg8zV2b0SYMHIJrghRGxB0hQuonAkzoQkXUWucTXxEnNGl2FD5qU4GgWCL0jJmP4S5iKYujq6LFMacU25i0yMX3Jt8WN1lrosBZyETb38EWaupg9G4IQRxExw?width=1059&height=464&cropmode=none)

**Comment by pedroSG94** [comment] 2019-12-23 17:47
This error is in a different line.
I did a fix for it. Try compile this library version:
```
implementation 'com.github.pedroSG94:rtplibrary:34df678ec8'
```
Also this error look that you are using differents threads to call stop in onVideoDecodeFinished and in onConnectionFailedRtmp. I recommend you use main thread in both sides like here to avoid threads sync error (this could be your problem):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/filestreamexample/RtmpFromFileActivity.java#L99

**Comment by MohammadRezaei92** [comment] 2020-01-06 15:50
> This error is in a different line.
> I did a fix for it. Try compile this library version:
> 
> ```
> implementation 'com.github.pedroSG94:rtplibrary:34df678ec8'
> ```
> 
> Also this error seems that you are using differents threads to call stop in onVideoDecodeFinished and in onConnectionFailedRtmp. I recommend you use main thread in both sides like here to avoid threads sync error (this could be your problem):
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/filestreamexample/RtmpFromFileActivity.java#L99

I used this version and I got this error on RtmpDisplay on prepareVideo:
`E/VideoEncoder: Create VideoEncoder failed.
    android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1960)
        at android.media.MediaCodec.configure(MediaCodec.java:1889)
        at com.pedro.encoder.video.VideoEncoder.prepareVideoEncoder(VideoEncoder.java:128)
        at com.pedro.rtplibrary.base.DisplayBase.prepareVideo(DisplayBase.java:110)
        at com.pedro.rtplibrary.base.DisplayBase.prepareVideo(DisplayBase.java:121)`

**Comment by pedroSG94** [comment] 2020-01-06 15:57
This seems that you are using a bad configuration. Try with default prepareVideo to discard it.
Can you share prepareVideo configuration used?
Also tell me device model and API

**Comment by MohammadRezaei92** [comment] 2020-01-06 18:07
> This seems that you are using a bad configuration. Try with default prepareVideo to discard it.
> Can you share prepareVideo configuration used?
> Also tell me device model and API

It was working before I updated it to `34df678ec8`
It's prepareVideo
`val videoSize = resources.displayMetrics`
                `rtmpDisplay.prepareVideo(
                            videoSize.widthPixels
                            , videoSize.heightPixels, liveCreatedResponse?.streamVideoFps!!
                            , liveCreatedResponse?.streamVideoBitRate!!
                            , 0, videoSize.density.toInt())`
Device: Xiaomi Redmi Note 7  API 28

**Comment by pedroSG94** [comment] 2020-01-06 18:40
was it working in 1.7.4 version? I did nothing to that method
Can you share steps to reproduce this error?

**Comment by MohammadRezaei92** [comment] 2020-01-07 05:19
> was it working in 1.7.4 version? I did nothing to that method
> Can you share steps to reproduce this error?
> Can you tell me values of FPS and videobitrate?
Yea it was working.
Values for bitrate and fps depend on network connection speed, I use Instagram live API.
My code work on a Samsung galaxy j7 API 28 with the same Internet connection and arguments for prepareVideo as Note 7. just the video size is different.

**Comment by pedroSG94** [comment] 2020-01-08 11:05
Maybe this is the problem. Try with a low resolution to discard it (default prepareVideo if you can) and make sure that this resolution is multiple of 2.
Can you do a test with 1.7.4 version? because both versions use same code. Maybe this was working in other version.
Version 34df678ec8:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/34df678ec8726fbe37e85cfa160339f19f6c2598/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L72
Version 1.7.4:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/0c87c996a2c55b19e18903dd176fb0a39c152be5/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L72
Also show me info about your videoEncoder with this method:
```java
for (String s : CodecUtil.showAllCodecsInfo()) {
 Log.e("Codec", s);
}
```

**Comment by MohammadRezaei92** [comment] 2020-01-09 05:10
I fix the problem. It was an issue in android codec. as mentioned here: https://stackoverflow.com/a/40229942

**Comment by MohammadRezaei92** [comment] 2020-08-08 10:04
I found a new issue related to this topic
`com.pedro.encoder.input.decoder.AudioDecoder.decodeAudio (AudioDecoder.java:184)`
`Attempt to invoke virtual method 'void android.media.MediaCodec.releaseOutputBuffer(int, boolean)' on a null object reference`

**Comment by pedroSG94** [comment] 2020-08-10 22:31
Working on it.

**Comment by pedroSG94** [comment] 2020-08-13 17:09
I did 2 commits for decoders that should solve both errors:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commits?author=pedroSG94

**Comment by MohammadRezaei92** [comment] 2020-08-18 10:07
Still have error on video decoder
`Fatal Exception: java.lang.NullPointerException`
`Attempt to invoke virtual method 'void java.lang.Thread.interrupt() on a null object reference`
`com.pedro.encoder.input.decoder.VideoDecoder.stop(VideoDecoder.java:101)`

**Comment by pedroSG94** [comment] 2020-08-18 14:11
Are you using last commit? That line is not a thread interrupt:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/decoder/VideoDecoder.java#L101
Your line is an old commit. You are using library in 1.8.5 version no my last commit.
I did a commit and I uploaded new library version. Try with this gradle:
```
  implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:1.8.6'
```

**Closed** 2021-04-19 11:56 UTC
