### ISSUE TITLE
Audio & Video Synchronization Delay when Streaming and Recording with OpenGl RTMP

### ISSUE THREAD

**Issue by naco95** [pedroSG94/rtmp-rtsp-stream-client-java#738] opened 2020-12-01 16:50 UTC
Hello, 

When testing streaming and recording simultaneously with Huawei P9 lite, Android 6, a delay it's noticeable. 
Lets say audio is 1 second before the video.  I noticed the same also in Android 7, the delay I think was less than 1 second.
While in Android 8, 9 and 10 it didn't had any issue.

Also I've tried doing only recording without streaming, the same problem of audio video sync problem, the audio is before the video.

All the tries were with the OpenGl RTMP, using the default params, while when using Custom Mode, Surface Mode & Texture Mode is seems to be ok, audio and video are synchronized.

In there any way that handle this problem, if there is could you point me please. Thanks in advance.

**Comment by pedroSG94** [comment] 2020-12-02 13:10
Huawei P9 lite is working in Android 8, 9 and 10 or you mean other device?

**Comment by naco95** [comment] 2020-12-02 13:18
Sorry for not making my self clear.

I'm having this sync problem in Huawei p9 lite, running Android 6.

While in other devices that I've tested running with Android 8, 9, & 10 is working perfect.

**Comment by pedroSG94** [comment] 2020-12-09 11:26
Sorry for late response. I was in holydays.

Unfortunatelly after test with a Samsung S7 with Android 6 I can't reproduce the problem so I can discard Android 6 problem.
I will test in other devices and try repoduce it but I'm not sure if I can do it.

**Comment by naco95** [comment] 2020-12-09 13:29
Hello,

Thanks for taking time to consider the problem described above. Based on your test, I think the problem could be device related. Maybe the Huawei P9 lite is not powerful enough and  it may take some time to render and write the video frame comparing to the audio frame. 
This is just a supposition of mine and I could be wrong. 
Again thank you, for making time. If you are able to reproduce it, please let me know if I can help you with something

**Comment by pedroSG94** [comment] 2020-12-23 09:53
This should be fixed now:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/8d5d94425211f0b14a56c5f5eb43cdc61beafc4e
Reopen the issue if you have any problem.

**Closed by pedroSG94** 2020-12-23 09:53 UTC
