### ISSUE TITLE
LayoutParams cannot be cast to AbsListView LayoutParams 

### ISSUE THREAD

**Issue by ozankonur** [pedroSG94/rtmp-rtsp-stream-client-java#64] opened 2017-10-11 06:54 UTC
Logs:

Process: com.pedro.rtmpstreamer, PID: 18412
                                                                        java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
                                                                            at android.widget.GridView.onMeasure(GridView.java:1046)
                                                                            at android.view.View.measure(View.java:16736)
                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5184)
                                                                            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                            at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                            at android.view.View.measure(View.java:16736)
                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5184)
                                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                            at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                            at android.view.View.measure(View.java:16736)
                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5184)
                                                                            at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:393)
                                                                            at android.view.View.measure(View.java:16736)
                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5184)
                                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                            at android.view.View.measure(View.java:16736)
                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5184)
                                                                            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                            at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                            at android.view.View.measure(View.java:16736)
                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5184)
                                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2392)
                                                                            at android.view.View.measure(View.java:16736)
                                                                            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2103)
                                                                            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1402)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1103)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6018)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:799)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:599)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:559)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:784)
                                                                            at android.os.Handler.handleCallback(Handler.java:733)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:157)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5872)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by pedroSG94** [comment] 2017-10-11 07:12
I can't see error line in that log... 
Are you using my app?
Where crash?

**Comment by ozankonur** [comment] 2017-10-11 07:15
Yes I am using your app, I think there is something on runtime can be about LayoutParams

**Comment by pedroSG94** [comment] 2017-10-11 07:16
Can you tell me the line? In that log I can't see any line of the Activity.

**Comment by pedroSG94** [comment] 2017-10-11 07:37
Ok. This could be the error. Go to MainActivity and in line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtmpstreamer/MainActivity.java#L217

Delete it and add the line before:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtmpstreamer/MainActivity.java#L221

If the problem is solved let me know to add the fix.

**Comment by ozankonur** [comment] 2017-10-11 07:39
some thing like that ?

 if (convertView == null) {
        button = new TextView(parent.getContext());
        button.setTextSize(TypedValue.COMPLEX_UNIT_PX, fontSize);
        button.setTextColor(ResourcesCompat.getColor(resources, R.color.white, null));
        button.setBackgroundColor(ResourcesCompat.getColor(resources, R.color.appColor, null));
        button.setLayoutParams(params);
        button.setPadding(padding_h, padding_v, padding_h, padding_v);
        button.setGravity(Gravity.CENTER);
        button.setText(links.get(position).getLabel());
      } else {
        button = (TextView) convertView;
      }
      return convertView;

**Comment by pedroSG94** [comment] 2017-10-11 07:46
```java
if (convertView == null) {
        button = new TextView(parent.getContext());
        button.setTextSize(TypedValue.COMPLEX_UNIT_PX, fontSize);
        button.setTextColor(ResourcesCompat.getColor(resources, R.color.white, null));
        button.setBackgroundColor(ResourcesCompat.getColor(resources, R.color.appColor, null));
        button.setLayoutParams(params);
        button.setPadding(padding_h, padding_v, padding_h, padding_v);
        button.setGravity(Gravity.CENTER);
      } else {
        button = (TextView) convertView;
      }
      convertView = button;
      button.setText(links.get(position).getLabel());
      return convertView;
```

**Comment by ozankonur** [comment] 2017-10-11 07:48
No, it isn't fix the problem. I think the problem is about rendering layouts

**Comment by pedroSG94** [comment] 2017-10-11 07:49
The problem is with gridview acording to this post:
https://stackoverflow.com/questions/31601129/android-java-lang-classcastexception-android-widget-linearlayoutlayoutparams-c

Can you tell me API used?

**Comment by ozankonur** [comment] 2017-10-11 07:50
API Level: 19

**Comment by pedroSG94** [comment] 2017-10-11 08:46
Fixed in last commit.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/e3e5c39600384cfc2dda9869270434ad0e7d5e85

**Closed** 2017-10-11 10:21 UTC
