### ISSUE TITLE
CalledFromWrongThreadException with AndroidViewFilterRender

### ISSUE THREAD

**Issue by b95505017** [pedroSG94/rtmp-rtsp-stream-client-java#159] opened 2018-04-10 09:12 UTC
AndroidViewFilterRender rely on `draw` of View, but `drawFilter` doesn't run on UI thread, is there any  recommended solution?

**Comment by b95505017** [comment] 2018-04-10 15:26
@pedroSG94 I think the main problem is the `drawFilter` doesn't called on UI thread, if we share the same View object in Activity window and AndroidViewFilterRender, we may meet the CalledFromWrongThreadException.

**Comment by pedroSG94** [comment] 2018-04-10 15:38
Can you share a code to reproduce error?

**Comment by b95505017** [comment] 2018-04-10 15:47
It can't always reproduce.
```java
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6891)
        at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1083)
        at android.view.ViewGroup.invalidateChild(ViewGroup.java:5205)
        at android.view.View.invalidateInternal(View.java:13656)
        at android.view.View.invalidate(View.java:13592)
        at android.view.View.invalidateDrawable(View.java:17804)
        at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:435)
        at android.graphics.drawable.Drawable.setBounds(Drawable.java:214)
        at android.view.View.setBackgroundBounds(View.java:17392)
        at android.view.View.drawBackground(View.java:17359)
        at android.view.View.draw(View.java:17176)
        at android.view.View.draw(View.java:17093)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1651)
        at android.view.View.draw(View.java:17188)
        at com.pedro.encoder.input.gl.render.filters.AndroidViewFilterRender.drawFilter(AndroidViewFilterRender.java:82)
```

**Comment by pedroSG94** [comment] 2018-04-13 19:54
this should be fixed now: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/6848652d8d2caf8ebb03915077e57bd40b9cb41c

**Comment by b95505017** [comment] 2018-04-13 20:04
@pedroSG94 Thanks, will this change makes lots of Runnable objects being generated?

**Comment by pedroSG94** [comment] 2018-04-14 08:59
No none will be generated, this change use main thread to execute draw method so I am only reusing this thread.

**Comment by b95505017** [comment] 2018-04-14 14:28
I mean this:
```java
mainHandler.post(new Runnable() {
```
Which may generate a new Runnable object for each opengl drawing frame?

**Comment by pedroSG94** [comment] 2018-04-14 19:38
Yes, but no more than one runnable at same time because handler block it.

**Closed** 2018-05-10 13:49 UTC
