### ISSUE TITLE
iOS VideoJS issue

### ISSUE THREAD

**Issue by mylaimani** [pedroSG94/rtmp-rtsp-stream-client-java#977] opened 2021-11-16 09:39 UTC
I am trying to live stream from Android app to Wowza Server. When I play the live stream in VideoJS iOS Safari I am getting following error (the same is working fine in MacOS Google Chrome but still not in iOS Chrome)

VIDEOJS: – "ERROR:" – "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)" – "The media could not be loaded, either because the server or network failed or because the format is not supported."
MediaError

code: 4

message: "The media could not be loaded, either because the server or network failed or because the format is not supported."

MediaError Prototype

Is this error has anything to do with our streaming app ?

**Comment by pedroSG94** [comment] 2021-11-16 10:32
Hello,

I recently did a fix to rtmp module that could be related with your case. Can you compile app example and check that you can reproduce the error?
After that, if you can provide me a way to test that player to reproduce the problem. I need to know wowza, safari and chrome versions to reproduce the problem.

**Comment by mylaimani** [comment] 2021-11-16 11:44
This is the code I am using for player

`<!DOCTYPE html>
<html>
<head>
    <meta charset=utf-8 />
    <title>videojs-contrib-hls embed</title>
    <link href="https://unpkg.com/video.js/dist/video-js.css" rel="stylesheet">
</head>
<body>
<h1>Video.js Example Embed</h1>

<video-js id="my_video_1" class="vjs-default-skin" data-setup='{"liveui": true}' controls preload="auto" width="640" height="268">
    <source
            src="https://wowzaprod282-i.akamaihd.net/hls/live/1022940/3fe467a5/playlist.m3u8"
            type="application/x-mpegURL">
</video-js>

<script src="https://unpkg.com/video.js/dist/video.js"></script>
<script src="https://unpkg.com/@videojs/http-streaming/dist/videojs-http-streaming.js"></script>

<script>
    var player = videojs('my_video_1', {liveui: true});
</script>

</body>
</html>`

I am using  

Wowza Version: 4.8.14+9
MacOS Safari Version: Version 15.1 (17612.2.9.1.20)
iOS version 15.1
Chrome Version 95.0.4638.69 (Official Build) (x86_64)

**Comment by mylaimani** [comment] 2021-11-16 11:49
I downloaded the latest version of RTMP client and tested live streaming, still getting the same problem

**Comment by pedroSG94** [comment] 2021-11-16 12:24
I will try reproduce your case an report you back.

> I downloaded the latest version of RTMP client and tested live streaming, still getting the same problem

This fix is not included on gradle. You need download it manually or compile master branch project

**Comment by mylaimani** [comment] 2021-11-16 12:59
Today morning only I downloaded the code manually from master branch. I will download again now, test it and update you

**Comment by mylaimani** [comment] 2021-11-16 14:20
I downloaded the code from Master branch and run the application, still facing the same problem, I am sending you the screenshots

<img width="1548" alt="Screenshot 2021-11-16 at 7 47 07 PM" src="https://user-images.githubusercontent.com/4998347/142001942-3ca9bb22-9d8f-45d4-953f-a45ee97d52fe.png">

![WhatsApp Image 2021-11-16 at 7 48 36 PM](https://user-images.githubusercontent.com/4998347/142002205-63e1f287-7876-4a06-a131-9977537d7d27.jpeg)

**Comment by mylaimani** [comment] 2021-11-17 10:55
Do you know any other html player that can work for both Android and iOS browsers

**Comment by pedroSG94** [comment] 2021-11-17 11:11
Hello,

I'm still testing it.
For now, I tested Safari and Chrome in iPad and MacOS ARM (I haven't a MacOS x86_64).

I did a test with a local server but it isn't wowza. I'm using this one:
https://github.com/aler9/rtsp-simple-server

It is working in all cases for me the only problem is that on iPad it take so much time to load the player and the delay is high.
I will try to get a trial of wowza and report you back if I can reproduce the problem.

About other player, I don't know so much on browser side but use video tag of html directly or this should be a good option:
https://github.com/video-dev/hls.js

**Comment by mylaimani** [comment] 2021-11-17 11:51
I tested hls.js it is working in Android phone, Mac computer and Windows computer but it did not work in iPhone. Unable to understand the reason for this problem

**Comment by mylaimani** [comment] 2021-11-17 11:54
I use this application to stream for Facebook, at that time all the HTML players are working perfectly in Mac Safari, iOS Safari, Android Chrome...

Now even in iOS Google chrome also not working.

**Comment by pedroSG94** [comment] 2021-11-17 12:04
You have the reason here:
https://github.com/video-dev/hls.js/issues/4354
Check if the workaround is working for you. Maybe, use 2 players depend if you are using iOS or not is a solution.
I can't help you so much here because I haven't iPhone and seems that iPad is supported by that library.

**Comment by mylaimani** [comment] 2021-11-17 13:34
Resolved the problem, the issue is in Wowza Streaming Engine itself, after discussing with Wowza and updating, everything works fine

**Comment by pedroSG94** [comment] 2021-11-17 18:04
That is a good news. Closing issue.

**Closed by pedroSG94** 2021-11-17 18:04 UTC
Labels: question

**Comment by biviel** [comment] 2021-11-22 20:56
@mylaimani , I'm also using Wowza Streaming Engine, could you share please what was the issue with your Wowza? Which version are you running? Thanks!

**Comment by mylaimani** [comment] 2021-11-23 07:18
@biviel At present I am using Wowza 4.8.15+3 

Before this version, the live stream **.m3u8** format did not work properly in apple devices (iOS and MacOS)

version 4.8.15+3 fixed this problem.
