### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by zlz3371062** [pedroSG94/rtmp-rtsp-stream-client-java#1092] opened 2022-04-18 00:46 UTC
i pushed my screen .the screen  is playing a video with hardware acceleration  , then  i found i can not push the player ,it is black

**Comment by pedroSG94** [comment] 2022-04-19 09:59
Hello,

Screen need to be updated to create video packets. Also, you can force render to avoid this problem like this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/displayexample/DisplayService.kt#L71
Did you try my app example to know if it is working fine?

**Comment by zlz3371062** [comment] 2022-04-22 08:02
![147611650613424_ pic](https://user-images.githubusercontent.com/16331669/164637660-ff6cbb89-780a-45c7-8a4c-1d9b79a2cf0f.jpg)
i force render  but it does not work .
i  recorded as a mp4 file when push  rtsp stream  .
the mp4 file can not show  the picture in vlc player

**Comment by zlz3371062** [comment] 2022-04-22 08:10
The app example is working fine. I can record screen into a mp4 file. But the media player in my screen with hardware acceleration opening has no picture，just audio.

But it cat get picture when the player's hardware acceleration mode was turn off.
ps: 1 other apps is also work like this .
      2.my device is a  android tv whit a poor cpu

**Comment by zlz3371062** [comment] 2022-04-22 08:14
sorry   for my poor english . Can you understand me

**Comment by pedroSG94** [comment] 2022-04-22 08:27
So, you only have problems reproducing a recorded video with VLC with hardware acceleration mode on.

In this case this seems a VLC problem. If you can reproduce video without hardware acceleration or in other player it seems a problem in VLC with hardware acceleration in your device.

Try to test using a file recorded using camera in my app to discard totally a problem with forcerender method.

**Comment by zlz3371062** [comment] 2022-04-22 10:13
forcerender method   work well ,
it seems that  i can not reproduce video whit hardware acceleration in other apps and  players in that device (android tv) but  other device   work  well
i think the devices have problems.....

**Comment by pedroSG94** [comment] 2022-04-22 10:29
If you have problems with VLC you should ask in VLC forum not here because I can't do anything about it:
https://forum.videolan.org/viewforum.php?f=32
If you have any other problem related with the library you can open an issue. I hope you can find a solution

Closing issue since it is not related with my library.

**Closed by pedroSG94** 2022-04-22 10:30 UTC

**Comment by romio95** [comment] 2022-06-30 11:17
Hi, this plugin is really cool! Thank you!

I have a question. While recording the broadcast, my screen becomes inactive and it locks. And after unlocking, the stream ends. How to prevent the screen from being blocked while the broadcast is being recorded?

**Comment by pedroSG94** [comment] 2022-06-30 17:18
https://stackoverflow.com/questions/9335908/how-to-prevent-the-screen-of-an-android-device-to-turn-off-during-the-execution#:~:text=Add%20android%3AkeepScreenOn%3D%22true,will%20not%20turn%20off%20automatically.
