### ISSUE TITLE
Preview quality deteriorated when using rtmpCamera2 with OpenGl

### ISSUE THREAD

**Issue by florianmlr** [pedroSG94/rtmp-rtsp-stream-client-java#963] opened 2021-10-28 17:35 UTC
Hello Pedro,
First of all, thank you for this work and thank you for sharing this library.

I took a look at your sample and I was interested about using Camera2 with OpenGl as in your sample you're using Camera1 with openGl. 
So I simply replaced the `RtmpCamera1` with `RtmpCamera2` in the `OpenGlRtmpActivity`, it works fine however I've noticed that the preview quality decrease when using RtmpCamera2.

Below 2 screenshots to compare RtmpCamera1 (left) and RtmpCamera2 (right).

<img src="https://user-images.githubusercontent.com/92301086/139303144-388cbb76-dee6-440f-944e-52f49008009c.png" width="100" />    <img src="https://user-images.githubusercontent.com/92301086/139303182-150f27a1-23ec-49c3-80e0-219cfc7578e3.png" width="100" />

I took theses screenshots with a Pixel 4a, and set the `prepareVideo` function with theses values : ```prepareVideo(1280, 720, 30, 2000 * 1024, 0)``` and no filter selected in both case. Enable or disable "FXAA" didn't change anything.

I stil can't figure out why the preview quality decrease when using RtmpCamera2, do you have an answer to that ?
Btw i have also noticed that preview quality is lower when using OpenGlView instead of a SurfaceView, for what reason ?

**Comment by pedroSG94** [comment] 2021-11-02 08:55
Hello,

I was doing multiple test to try find the error but I'm not able to reproduce or find any similar case on web.
I want to ask you few questions and after that. I will try get a way to test with a Pixel 4a to reproduce your case:
- Do you have Pixel 4a or Pixel 4a 5G? china room or international room?
- Can you test it with other device to know if it is only a problem with a device?
- Can you try stream using SurfaceView an textureview examples (camera2) and compare stream result with OpenGlView? (the stream result should be the same that OpenGlView but the preview should be better with SurfaceView and TextureView)

**Comment by florianmlr** [comment] 2021-11-02 10:22
Hello,
I have Pixel 4a (Android 11), international room.

I've tried to reproduce it with a Samsung A5 (Android 8) and i can't reproduce it. The quality is good with camera2 (right)
<img src="https://user-images.githubusercontent.com/92301086/139825666-7a0d8719-46cf-44f0-bfb1-f81e14f4472e.jpg" width="100" />  <img src="https://user-images.githubusercontent.com/92301086/139825689-a164c848-ada8-4930-9bcb-4de85bc9057c.jpg" width="100" />

Yes here is the comparison from a Twitch live with openglview (left) and surfaceview (right) , both with camera2.
<img width="100" alt="Capture d’écran 2021-11-02 à 11 12 40" src="https://user-images.githubusercontent.com/92301086/139828015-ed621988-92ad-4e15-8bff-f444f72cb1e4.png"> <img width="100" alt="Capture d’écran 2021-11-02 à 11 11 39" src="https://user-images.githubusercontent.com/92301086/139828033-1dc013eb-0407-4b7b-a734-ffcf2be82fea.png">
Also, i have noticed that the quality of the preview from surfaceview is better

**Comment by pedroSG94** [comment] 2021-11-07 21:02
I got a Pixel 4a today. It will take few days until I receive device and I will try fix this case.

**Comment by florianmlr** [comment] 2021-11-29 16:47
Hello Pedro, could you reproduce it on your Pixel 4a ?

**Comment by pedroSG94** [comment] 2021-11-29 23:28
Hello,

Sorry but I was doing tests 2 days and I can't find the reason about it. I will try again tomorrow.

**Comment by pedroSG94** [comment] 2021-11-30 12:56
I think that the problem is fixed:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/pixel4a

Compile that branch and let me know if it is working for you

**Comment by florianmlr** [comment] 2021-11-30 14:10
Hello, thank you for the fix, it works ! 
The quality has been improved
Btw I had done some research on my side and noticed that another library had the same issue (https://github.com/natario1/CameraView/pull/1089/files) and they added the pixel 4 as well, should we add it too ?

**Comment by pedroSG94** [comment] 2021-11-30 14:20
Maybe yes, but the error seems different and the fps range filters is different too.
In my case the fps ranges with problems was 15-15, 15-30 and 30-30 and is working fine 15-60 and 60-60.
Can you comfirm it?

**Comment by florianmlr** [comment] 2021-12-06 16:32
Currently I don't have a pixel 4, i can't confirm it sorry but I can confirm that this fix works for pixel 4a, thank you

**Comment by pedroSG94** [comment] 2021-12-08 22:08
I will keep pixel 4 without add until someone comfirm it since the error seems different to the other project. 
The commit was added to master. Closing issue.

**Closed by pedroSG94** 2021-12-08 22:09 UTC
