### ISSUE TITLE
How to preview filters ,watermarks before stream 

### ISSUE THREAD

**Issue by pratheepchowdhary** [pedroSG94/rtmp-rtsp-stream-client-java#155] opened 2018-03-30 06:13 UTC
Hello sir how to preview the filter effects and  watermarks before the stream  by apply effects and watermarks  before  stream it will not showing it while streaming only it works so please guide me sir

**Comment by pedroSG94** [comment] 2018-03-30 10:28
I can do it. I detect a crash with gif, images and text but it has a easy fix that will be update in the next days (no time now). To fix replace in openglview:
```java
//need load a stream object
            if (loadStreamObject) {
              if (textStreamObject != null) {
                managerRender.setText(textStreamObject);
              } else if (imageStreamObject != null) {
                managerRender.setImage(imageStreamObject);
              } else if (gifStreamObject != null) {
                managerRender.setGif(gifStreamObject);
              } else {
                managerRender.clear();
              }
            }
```

To:

```java
//need load a stream object
            if (loadStreamObject) {
              if (textStreamObject != null) {
                managerRender.setText(textStreamObject);
              } else if (imageStreamObject != null) {
                managerRender.setImage(imageStreamObject);
              } else if (gifStreamObject != null) {
                managerRender.setGif(gifStreamObject);
              } else {
                managerRender.clear();
              }
              if (surfaceManagerEncoder == null) loadStreamObject = false;
            }
```

**Comment by pratheepchowdhary** [comment] 2018-03-30 10:54
K
Thank you.....

**Comment by pedroSG94** [comment] 2018-03-31 10:25
No preview available streaming a file for now. It need be developed.

**Comment by pratheepchowdhary** [comment] 2018-04-03 07:46
K
How to make  AndroidViewFilter  fit to the video view width and height
Accordingly
Now it will show according screen resolution of mobile 
How to make it according to video resloution

**Comment by pedroSG94** [comment] 2018-04-03 07:59
Go xml, create a layout with match parent size and set it to androidviewfilter.
Now you have a layout that fit stream.
You can hide this layout behind other view to avoid duplicate view in the activity.

**Comment by pratheepchowdhary** [comment] 2018-04-03 08:34
Still remains the same issue 
It will takes the same screen size 
Is there is any way to fix it programmatically 
In canvas  by giving width and height of video

**Comment by pratheepchowdhary** [comment] 2018-04-09 16:26
please fix it bro

**Comment by pedroSG94** [comment] 2018-04-10 07:12
I try it but for now I can't find a solution. The problem is that you need resize canvas to adjust to stream resolution. I did severals test with a device 1920x1080 screen resolution and I cant find a mathematical relationship. If you are in portrait resize values is 1080x1530 (setted in this line: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/OffScreenGlThread.java#L203)

**Comment by pratheepchowdhary** [comment] 2018-04-16 09:36
K
Another issue is that  while adding jpg images as watermark in file stream the it will shows completly white screen with watermark image
I tried to convert jpg to png same result 
But I use already extended png images works good but with jpg come  white screen is there is any solution

**Comment by pedroSG94** [comment] 2018-04-16 12:47
Can you send me an image capture and jpg image that produce error?

**Comment by pratheepchowdhary** [comment] 2018-04-16 12:55
[
![screenshot_2018-04-16-18-21-31-400_com facebook katana](https://user-images.githubusercontent.com/13903537/38810065-4462ce34-41a3-11e8-9a15-c6592d4b8976.png)
](url)
The images shows video 

![676a12d7bd3f2ed99b3d13e6584ac1c8](https://user-images.githubusercontent.com/13903537/38810127-70021c8e-41a3-11e8-8ab7-f28f17b4a6fa.jpg)
This above show the icon watermark

**Comment by pedroSG94** [comment] 2018-04-16 13:02
Can you send me an image while you are streaming please?

**Comment by pratheepchowdhary** [comment] 2018-04-16 13:05
[](https://m.facebook.com/story.php?story_fbid=1227506437382002&id=100003679734430[](url))
What this video

**Comment by pratheepchowdhary** [comment] 2018-04-16 13:06
https://m.facebook.com/story.php?story_fbid=1227506437382002&id=100003679734430

**Comment by pedroSG94** [comment] 2018-04-16 13:29
Ok, I understand now.
jpg has not alpha so you can't provide a transparency like I do with png and if you convert a image jpg to png the result is a image without transparency because the original image has not it.
In this case:
0 -> 100% transparency
1 -> 0% transparency (opaque)

JPG image alpha always 1 because this format has not transparency then you convert to png that has transparency but original transparency is 1 so the result is png with 1 transparency.

How can you fix it (this is a concrete fix for your case)? using a concrete color like transparency (like in chroma stage with green color) in your case white color is good choice.

To do it go to watermark shader:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/res/raw/watermark_fragment.glsl#L14
Replace that line to:
```glsl
if (watermarkPixel.a <= 0.5 || watermarkPixel.rbg == vec3(1.0, 1.0, 1.0)) {
```
This will filter pure white color but I test and no totally filter in your case so I recommend you filter grey scale totally like:
```glsl
if (watermarkPixel.a <= 0.5 || (watermarkPixel.r == watermarkPixel.b && watermarkPixel.b == watermarkPixel.g)) {
```

**Comment by pedroSG94** [comment] 2018-04-16 13:40
Overlay in all stream size is fixed now: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/936e58afe92534f4fece30630890f8dfbb718140

**Comment by pratheepchowdhary** [comment] 2018-04-17 07:02
K it's working 
Thank u

**Closed** 2018-05-10 13:49 UTC
