### ISSUE TITLE
replaceView while streaming in background 

### ISSUE THREAD

**Issue by ggpaeg** [pedroSG94/rtmp-rtsp-stream-client-java#1011] opened 2021-12-14 07:20 UTC
Hi! 

I'm streaming with foreground service, camera2, opengl and rtmpCamera2.

While activity is opened and rotated to landscape, I can stream in landscape, 640x480. It's fine. 

My problem occurs when the activity gets destroy and openGl is replaced using replaceView(context) method.

When the view is replaced my stream changes completely, its like 480x640 and out of stream screen center. 

How can I maintain landscape stream 640x480 after replaceView(context)?

**Comment by pedroSG94** [comment] 2021-12-14 09:32
Fixed here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/97068b51adcd2261744386b4ebe01eb43737c37e
You can try compile it using commit tag because for now I'm working in other things that I want add to next release:
```gradle
	        implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:97068b51ad'
```

**Comment by ggpaeg** [comment] 2021-12-15 04:23
Thank you @pedroSG94, now it works on the previous resolution.

The new problem that I'm facing is regarding stream and recording rotation. 
Before streaming I lock orientation to landscape (sensor 90 degrees), and set rotation to 180, using the following method:

`camera2Base!!.prepareVideo(640, 480, 30, 1200 * 1024, 180)`

When the activity is open, and the view is an openGlView, everything is fine. 

When I close activity and replaceView(context) is called, view rotates back to 90 degrees. As the following images:

![landscape_whileOpened](https://user-images.githubusercontent.com/83527406/146122873-739c84f0-8ea7-482c-a54b-627d07fcb017.PNG)

![landscape_whenClosed](https://user-images.githubusercontent.com/83527406/146122892-981d426a-aadf-4704-a255-d8988b66d95c.PNG)





I believe that would be nice to preserve rotation, as we preserve resolution when replacing view. If it's not a interesting feature to have in library, what you recommend to manually set that rotation after replaceView(context)?

**Comment by pedroSG94** [comment] 2021-12-15 08:23
Hello,

This is working as you said for me (preserve rotation). How are you doing to reproduce the problem?
I'm only blocking this activity:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/AndroidManifest.xml#L106
To landscape:
```xml
    <activity
        android:name=".backgroundexample.BackgroundActivity"
        android:label="@string/service_rtp"
        android:screenOrientation="landscape"
        />
```
And then use RTP service in my app to reproduce the case.

**Comment by ggpaeg** [comment] 2021-12-17 04:34
Hi Pedro! 

Rotation and resolution are working now. Thank you!

My current challenge is horizontal flipping. 
When the activity is opened I call `camera2Base.glInterface.setIsStreamHorizontalFlip(true)` to correct mirror effect.
      
When the activity is closed, code calls replaceView(context), and the stream is flipped again.
If I call `camera2Base.glInterface.setIsStreamHorizontalFlip(true)` again, the stream is still flipped. 

That behavior is fine from the library side? If it's expected, what can I do to correct the mirror effect after replacing the view?

**Comment by pedroSG94** [comment] 2021-12-17 10:51
Hello,

This is working for me. If you call setIsStreamHorizontalFlip after replaceView it is working as expected.
In my case to test I did this modifications.
In [RtpService class](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample/RtpService.kt) replace:
```kotlin
    fun setView(openGlView: OpenGlView) {
      this.openGlView = openGlView
      camera2Base?.replaceView(openGlView)
    }

    fun setView(context: Context) {
      contextApp = context
      this.openGlView = null
      camera2Base?.replaceView(context)
    }
```
To:
```kotlin
    fun setView(openGlView: OpenGlView) {
      this.openGlView = openGlView
      camera2Base?.replaceView(openGlView)
      camera2Base?.glInterface?.setIsStreamHorizontalFlip(true)
    }

    fun setView(context: Context) {
      contextApp = context
      this.openGlView = null
      camera2Base?.replaceView(context)
      camera2Base?.glInterface?.setIsStreamHorizontalFlip(true)
    }
```
Compile app and test with Service RTP example. As you can see the stream should be mirrored respect to preview and it keep mirrored if you close activity

**Comment by ggpaeg** [comment] 2021-12-17 19:37
Hi, 

The behavior is fine with device on portrait, 0 deegres. Issue happens when rotation = 90º. 

I'm using the following steps to reproduce that behavior:
Device rotation: Landscape 90º
Camera Facing: Front

Prepare Video method:
```
90 -> {
                //reverse landscape
                Log.d(TAG, "debug rotation 90")
                camera2Base!!.prepareVideo(640, 480, 30, 1500 * 1024, 180)
                //Flips on x axis
                camera2Base!!.glInterface.setIsStreamVerticalFlip(true)
                camera2Base!!.glInterface.setIsStreamHorizontalFlip(false)
                camera2Base!!.glInterface.setIsPreviewHorizontalFlip(true)
                camera2Base!!.glInterface.setStreamRotation(deviceRotation.value)
}
```
That code leads to correct behavior:

Stream:          
![CloseActivityStream](https://user-images.githubusercontent.com/83527406/146598209-00db3f3c-d1e4-4b6a-86ea-c73e2b53a80e.PNG)

Preview
![OpenActivity](https://user-images.githubusercontent.com/83527406/146598213-98bef71f-4a17-486f-a905-0e03ca9db940.PNG)

When activity is closed and setView(context) is called stream is flipped horizontally. 
If  `camera2Base!!.glInterface.setIsStreamHorizontalFlip(false)` is called after replaceView, it remains fliped. 

If `camera2Base!!.glInterface.setIsStreamHorizontalFlip(true)` stream flips correctly. 

The stream should be fliped after replaceView even with the same value for StreamHorizontalFlip? 

I'm doing something wrong?

**Comment by pedroSG94** [comment] 2021-12-18 16:50
I'm glad that all is working now.
I'm not sure if this is your case but front camera image is mirrored by default so if you use setIsStreamHorizontalFlip(true) that means mirror in back camera and no mirror in front camera because this method work under default image.

When you have all working as required close the issue. You can open a new issue or reopen it later if you have any question.

**Closed** 2021-12-18 19:57 UTC
