### ISSUE TITLE
Saving Record Failed Sometimes

### ISSUE THREAD

**Issue by disono** [pedroSG94/rtmp-rtsp-stream-client-java#142] opened 2018-03-12 17:04 UTC
I'm trying to save the recording while streaming but somethings the recording fails here is the logs when I tried to stop the recording:

Note: On some devices like Marshmallow (Real Device) the recording works perfectly without errors.
I tested this on Oreo API 26 (Emulator) where the errors occured or the recording is not saving.
```
E/MPEG4Writer: The number of recorded samples is 0
E/MPEG4Writer: Dumping Video track's last 10 frames timestamp 
E/MPEG4Writer: The number of recorded samples is 0
E/MPEG4Writer: Dumping Audio track's last 10 frames timestamp
```

Sample Codes:
```
    if (rtmpCameral.isStreaming()) {
      // stop recording
      if (rtmpCameral.isRecording()) {
          try {
             rtmpCameral.stopRecord();

             Toast.makeText(activity, "file " + currentDateAndTime + ".mp4 saved in " + folder.getAbsolutePath(), Toast.LENGTH_SHORT).show();
             currentDateAndTime = "";
             new VideoStream().scanFiles(getApplicationContext(), folder);

              // stop streaming
              rtspCameral.stopStream();
              rtspCameral.stopPreview();
          } catch (Exception e) {
              Log.e(TAG, "_stopRecording: " + e.getMessage());
          }
      } else {
        try {
          if (!folder.exists()) {
            folder.mkdir();
          }

          SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd_HHmmss", Locale.ENGLISH);
          currentDateAndTime = sdf.format(new Date());
          rtmpCameral.startRecord(folder.getAbsolutePath() + "/" + currentDateAndTime + ".mp4");
        } catch (IOException e) {
          rtmpCameral.stopRecord();
        }
      }
    }
```

**Comment by pedroSG94** [comment] 2018-03-12 21:44
This error normally is because mp4 file never receive a keyframe so no valid data is found.
In my case the result is a not playable file but no a crash I will try reproduce your case but use this library on emulator is a bad idea because normally emulators don't support encoding/decoding and opengl.
What emulator model are you using? Architecture?

**Comment by disono** [comment] 2018-03-13 02:46
This works sometimes (Emulator) but most of the time fails to save the file, the file created but unplayable:
Android 8.0 Nexus 5X API 26 x86 (Oreo)

Never works (Emulators):
Nexus 5X API 25 (Nougat) x86
Nexus 5X API 18 (Jelly Bean) x86
Nexus 4 API 22 (Marsmallow) x86_64

Logs:
I/SrsFlvMuxer: worker: send frame type=9, dts=42542, size=131072B
I/SrsFlvMuxer: worker: send frame type=9, dts=126, size=131072B
I/SrsFlvMuxer: worker: send frame type=9, dts=126, size=131072B

**Comment by pedroSG94** [comment] 2018-03-13 17:25
This error should be fixed now: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/55ae55cd6b2026bcd90dbd80a8e3935fe62fc4fb

**Closed** 2018-03-14 01:28 UTC
