### ISSUE TITLE
CameraDevice.close is hanging 

### ISSUE THREAD

**Issue by Shanmugamsundarrajan** [pedroSG94/rtmp-rtsp-stream-client-java#140] opened 2018-03-08 17:56 UTC
CameraDevice.close is hanging if tried to close when the TCP connection is disconnected in the middle of streaming. 
If closed after the complete streaming, its work fine

**Comment by Shanmugamsundarrajan** [comment] 2018-03-08 18:19
is it ok to stop the videoencoder , audioencoder before closing the camera
in the stopstream function

**Comment by pedroSG94** [comment] 2018-03-08 19:43
The problem is that camera stop preview when you call stopStream and not with stopPreview using camera2?
This should be fixed now: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/b08856f5112fbbdc4b470be142cf344b22352648

**Comment by Shanmugamsundarrajan** [comment] 2018-03-09 07:03
I am using RTSPCamer2  and Camera2Base and Camera2APIManager.

Shall I take the fixes as suggested by you. Do I need to change in all the files you have mentioned?

**Comment by pedroSG94** [comment] 2018-03-09 09:08
No, no I show you the commit to confirm that the problem was solved like you mentioned. The rest is features and more fixs. This line should fix your problem if I understand you:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/b08856f5112fbbdc4b470be142cf344b22352648#diff-cb04f78f7b479e484a58bd4d777630d0R470

**Comment by Shanmugamsundarrajan** [comment] 2018-03-09 14:20
Ok, I will take the latest update.  
I am using (with context)
One more issue i am facing, that is, sometimes I am not getting the preparevideo.
The prepareVideo is returning false.
 If that condition comes while the code is running how to resolve it (our requirement is to run in the back ground continuously

**Comment by pedroSG94** [comment] 2018-03-09 16:13
return false with the same device?
In this case, it is rare I need test it. In my opinion, the only way for it is videoencoder creation crash in this lines:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L118
Next time check log if you can to know the problem, normally this is for try crate when it is still created or use unsupported configuration

**Comment by Shanmugamsundarrajan** [comment] 2018-03-10 03:51
Yes its  returning false with the same device.

In that case how to get rid of this?  should we set the VideoEncoder to null or something? So that the next prepareVideo will be OK.

**Comment by pedroSG94** [comment] 2018-03-10 12:00
I did a little refactor with a fix for camera2 background. Now you don't need call stopPreview if you are using background mode, only stopStream is necessary. This could be your problem. 
Are you calling stopPreview after stopStream?
If not your camera is not stopped, only stream is stopped. Try get last commit. If the problem persist post the log when your method prepareVideo return false, you should see a log error with VideoEncoder tag like int this lines:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L85
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L90
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L119

**Comment by Shanmugamsundarrajan** [comment] 2018-03-11 07:06
I think the problem is due to the Camera not closing properly and when tried to open again this problem happens. 
The exception I am getting is Illegal state exception. If that happens, how to get rid of this.
Can I close the VideoEncoder already opened.
On getting Illegal State exception, how to close completely the video encoder and camera which is opened earlier and not closed.

**Comment by Shanmugamsundarrajan** [comment] 2018-03-11 07:09
You will find the problem when you try to start and stop the stream during the network failure.

**Comment by Shanmugamsundarrajan** [comment] 2018-03-11 07:17
I found one more issue in the RTSPClient  connect and disconnect. When the network failure happens, the writer.write   and reader.readLine() goes into blocking mode and the thread hangs. 

Before reader.readLine(), it is good to have  if(connectionSocket.getInputStream().available() > 0) {

**Comment by pedroSG94** [comment] 2018-03-11 15:36
How do you do network failure?
I tried close server connection, disable wifi and data mobile but no error.
Are you stopping stream in onConnectionFailedRtsp callback?
I'm doing my test in SurfaceModeRtspActivity class. Simply replace surfaceview in the constructor to context and delete surfaceview callback.

**Comment by Shanmugamsundarrajan** [comment] 2018-03-13 07:23
In our case of testing, we remove the wifi antenna, 
1. so the connection happens successfully and the further video streaming fails
2. Connection is ok, sending the announce is OK, will on receive the response. 

In these above two cases the code hangs, I have fixed the same.
But my main problem is the camera device closing. Some times take more time to close and hangs.

**Comment by Shanmugamsundarrajan** [comment] 2018-03-13 07:46
I have with few questions with you.
1. If you are running the camera in background, is it necessary to "startPreview"  onOpened 
2. What is importance of "clockVideoFrequency = 90000;" in RtpConstants

**Comment by pedroSG94** [comment] 2018-03-13 08:03
1 - You don't need use preview method when you use background mode. You can work with startStream and stopStream only (remember get las commit to fix the error closing with stopStream in background mode).
2 - clockVideoFrequency is only for sync audio and video.
The fix on connection is use:
```
 if(connectionSocket.getInputStream().available() > 0) {
}
```
Before use readline on getResponse method right? I want add this to my project. 
I will try reproduce your error but for now I never found this error. 
Are you using multithreading? maybe it is a synchronization thread.

**Comment by Shanmugamsundarrajan** [comment] 2018-03-13 08:28
You can simulate the error,
1. Have Wifi enabled  and open the connection.
2. Immediately after opening the connection disable the wifi.  (the send announce should go through and while getting the response you disable the wifi  and see what happens

Coming back to start preview.
Shall I comment the startPreview  call in the function onOpened

**Comment by pedroSG94** [comment] 2018-03-13 17:28
RtspClient hang should be fixed in this commit: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/9431fd6989f8fdeb2e969d79d9643fb7d4982996
For now, I can't reproduce prepareVideo return false sometimes or hang camera2. :(

**Comment by Shanmugamsundarrajan** [comment] 2018-03-29 14:34
The problem i am facing is:
For some reason the opened camera is not getting closed, then try to open again, the code is crashing.

I have two threads, 
a. one for taking image and sending to server
b. other one streaming video and recording the same.  
  
For some reason and very rarely the video thread is not closing the camera,  after that the image thread tries to open the camera, the code crashes.
Is there any way to force close camera open with all other like h264packet , aacpacket , audio encoder, video encoder.

**Comment by pedroSG94** [comment] 2018-03-30 10:59
try check if preview is enabled with isOnPreview method and use stopPreview if  true before startStream

**Closed** 2018-05-10 13:47 UTC
